### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SharafatKarim** [redwan-hossain/lazypac#1]
An way to list all installed(explicitly/ dependency) applications. And if the list is too large then pipe it to a text file or upload to a text-pasting online service

**Comment by md-redwan-hossain** [comment]
Will look into it. Give me some example search keyword that produces a long result list.

**Comment by SharafatKarim** [comment]
Sure! To get all software's list (explicitly installed + dependency), (system package + manually installed later + dependency)
```
pacman -Q
```
To get only explicitly installed applications (system package + manually installed later + not dependency)
```
pacman -Qe
```
To get only explicitly installed app (not system package + manually installed later  + not dependency)
```
pacman -Qet
```
To get only dependency, aka orphans, (not system package + not manually installed later +  dependency)
```
pacman -Qdt
```

**Comment by md-redwan-hossain** [comment]
Added in the latest commit. Check now.

**Comment by SharafatKarim** [comment]
thanks a lot, brother
